package com.crickex.india.crickex.btcwithmvvm.ui.login.model.viewGr

data class ViewGrModelItem(
    val Address1: String,
    val Address2: Any,
    val BlngFrmCode: Int,
    val CCActValidity: Any,
    val ChNo: Int,
    val CnsneNm: String,
    val CnsnrAdd: String,
    val CnsrNm: String,
    val CommonCarrierAct: Any,
    val CompanyName: String,
    val ConsigneeGSTNo: Any,
    val ConsignerGSTNo: Any,
    val ConsneAdd: String,
    val EWayBillNo: String,
    val Eml: Any,
    val FasaiLicNo: Any,
    val FromStnName: String,
    val GRDt: String,
    val GREntryBy: String,
    val GREntryDate: String,
    val GRNo: Int,
    val GSTNo: Any,
    val Goods: Any,
    val ISORegNo: Any,
    val ItemCount: String,
    val PANNo: String,
    val PhoneNo: String,
    val PrtInvNo: String,
    val Quantity: Any,
    val TGRAmt: Any,
    val ToStnName: String,
    val TrkIDNo: Int,
    val VehicleNo: String,
    val Webst: Any
)